spring.application.name=Notification-API-Service




messaging.provider.aws.enable = true
messaging.fallback.rabbitMq.enable = true
messaging.provider.Kafka.enable = true
messaging.fallback.Mqt.enable = true


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG